### ISSUE TITLE
Change Criteria of Rule 4 should be "=3"

### ISSUE THREAD

**Issue by florianhoh** [mrksdck/coderetreat-pocketmod#1]
In the illustration of the Game of Life rules the Change Criteria of Rule 4 should be "=3" rather than "=2", shouldn't it?

**Comment by mrksdck** [comment]
Yes, you are right.
Will fix

**Comment by mrksdck** [comment]
fixed : [coderetreat-pocketmod-booklet.pdf](https://github.com/mrksdck/coderetreat-pocketmod/files/3837966/coderetreat-pocketmod-booklet.pdf)

**Comment by mrksdck** [comment]
Thank you very much

**Comment by florianhoh** [comment]
Thank you very much for you quick fix, Markus
